# Generated by git-review's release workflow. Do not edit manually.
class GitReview < Formula
  desc "Review branch and working-tree changes in your terminal"
  homepage "https://github.com/cross-entropy-ai/git-review"
  version "1.9.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.9.1/git-review_darwin_arm64.tar.gz"
      sha256 "f70dec4e4551dbda6097b394814d40c375b024f8311893de22abd6bb8be057da"
    else
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.9.1/git-review_darwin_amd64.tar.gz"
      sha256 "8dad4b19db0130f348e32c5e94e664bfc3427f99c60cf98c49f574bd03e4d93d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.9.1/git-review_linux_arm64.tar.gz"
      sha256 "54b192a80d3b42a103fd291b8995f79745fbc052e1f348563529799b9f7a794b"
    else
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.9.1/git-review_linux_amd64.tar.gz"
      sha256 "51d48866d12d5f2d594a855fedc88431e23f2230af2cb279dcaf17a0e2de22e9"
    end
  end

  depends_on "git"

  def install
    bin.install "git-review"
  end

  test do
    assert_match "git-review #{version}", shell_output("#{bin}/git-review --version")
  end
end
