# Generated by git-review's release workflow. Do not edit manually.
class GitReview < Formula
  desc "Review branch and working-tree changes in your terminal"
  homepage "https://github.com/cross-entropy-ai/git-review"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.4.0/git-review_darwin_arm64.tar.gz"
      sha256 "e632b048eeba34e3df46246e9acd97dea1e3b08c7e971b33407442f8c990ea0b"
    else
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.4.0/git-review_darwin_amd64.tar.gz"
      sha256 "c88acebc6655a140176b26d292f4418181e7f6bca9c7d7326187370cb0484e7d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.4.0/git-review_linux_arm64.tar.gz"
      sha256 "6309a8139fd47b8c0548bed65cdc35b2b5e174c2a7c46736b689d6366f9bd0f5"
    else
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.4.0/git-review_linux_amd64.tar.gz"
      sha256 "b061d6edfa589f1043bc3dd17e846ba17cd4015c43bcf4789be31b0bec4a746c"
    end
  end

  depends_on "git"

  def install
    bin.install "git-review"
  end

  test do
    assert_match "git-review #{version}", shell_output("#{bin}/git-review --version")
  end
end
