# Generated by git-dashboard's release workflow. Do not edit manually.
class GitDashboard < Formula
  desc "Track repository activity and contributors in your terminal"
  homepage "https://github.com/cross-entropy-ai/git-dashboard"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-dashboard/releases/download/v0.1.0/git-dashboard_darwin_arm64.tar.gz"
      sha256 "7b5cdf0762e91d423ca7f9cb60b779356c86ed17fb7020d7b1e97e902e2caa26"
    else
      url "https://github.com/cross-entropy-ai/git-dashboard/releases/download/v0.1.0/git-dashboard_darwin_amd64.tar.gz"
      sha256 "80f40221ee5959f2ca06134c2533c3023078e5a01e12ac2ce7cc5f182f515b4d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-dashboard/releases/download/v0.1.0/git-dashboard_linux_arm64.tar.gz"
      sha256 "296c326b8a90b68687de963f7ad483e5490450b76f1c5acadb3f86bbba1d26da"
    else
      url "https://github.com/cross-entropy-ai/git-dashboard/releases/download/v0.1.0/git-dashboard_linux_amd64.tar.gz"
      sha256 "bc5887df211e9f83c881a6dd4b2941d72c257b1cf2a64e7bd74563c7d8682fa7"
    end
  end

  depends_on "git"

  def install
    bin.install "git-dashboard"
  end

  test do
    assert_equal "#{version}\n", shell_output("#{bin}/git-dashboard --version")
  end
end
