# Generated by git-review's release workflow. Do not edit manually.
class GitReview < Formula
  desc "Review branch and working-tree changes in your terminal"
  homepage "https://github.com/cross-entropy-ai/git-review"
  version "1.10.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.10.2/git-review_darwin_arm64.tar.gz"
      sha256 "ea48d0611a712930910be6c55524ebea4b9b9947a4a49faf6e840af54d1e4264"
    else
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.10.2/git-review_darwin_amd64.tar.gz"
      sha256 "cd89c8ee775817a5e55b2bf5177d378ab5522db7725bea2a0806cc3be8ed9633"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.10.2/git-review_linux_arm64.tar.gz"
      sha256 "b687980ce48b5040a097822f2a205f0b639448f7a3207f2da72a76d4ebfed132"
    else
      url "https://github.com/cross-entropy-ai/git-review/releases/download/v1.10.2/git-review_linux_amd64.tar.gz"
      sha256 "da2db8cb152215bbc77bda688cc69194ec5c174cc786c3c539781e090ba1332e"
    end
  end

  depends_on "git"

  def install
    bin.install "git-review"
  end

  test do
    assert_match "git-review #{version}", shell_output("#{bin}/git-review --version")
  end
end
