# Generated by webdrive's release workflow. Do not edit manually.
class Webdrive < Formula
  desc "Browse and manage files over HTTP from a single binary"
  homepage "https://github.com/cross-entropy-ai/webdrive"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.4/webdrive_darwin_arm64.tar.gz"
      sha256 "11ad11cf35145643f502ca78c36c6ace3d1753c8e272a65142e1b4b91d8bad46"
    else
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.4/webdrive_darwin_amd64.tar.gz"
      sha256 "490b9617116363f058f05478ef7ef0cd9006b0db8c74a27473cb63ba2af9fc9c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.4/webdrive_linux_arm64.tar.gz"
      sha256 "b45d6084898d7dec470b3e8b43b6e1aa7a77f4c69192400e58b54ef0a8b0f7fe"
    else
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.4/webdrive_linux_amd64.tar.gz"
      sha256 "28f549a09c1549557f001fb8a51bb38d398c8c2131e8fabefdf80af036dd15b1"
    end
  end

  def install
    bin.install "webdrive"
  end

  test do
    assert_match "webdrive serves", shell_output("#{bin}/webdrive --help")
  end
end
