# Generated by webdrive's release workflow. Do not edit manually.
class Webdrive < Formula
  desc "Browse and manage files over HTTP from a single binary"
  homepage "https://github.com/cross-entropy-ai/webdrive"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.6/webdrive_darwin_arm64.tar.gz"
      sha256 "d677e0fa3783e08b4765ac3901424e9b8eb3beeb94540cd830e1163ed81f61a4"
    else
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.6/webdrive_darwin_amd64.tar.gz"
      sha256 "07de8dc4aba832db9c43b4c966fb03c598513e4265a121d727608d80508283aa"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.6/webdrive_linux_arm64.tar.gz"
      sha256 "377d4077804a80e773f91b58b5bee62c4dc89a5a6679113a68e42ab2752066d4"
    else
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.1.6/webdrive_linux_amd64.tar.gz"
      sha256 "a836024cf26791f4c03193a0a6a24175c207e5fcc354fa0acb80cc61d69ad74b"
    end
  end

  def install
    bin.install "webdrive"
  end

  test do
    assert_match "webdrive serves", shell_output("#{bin}/webdrive --help")
  end
end
