# Generated by webdrive's release workflow. Do not edit manually.
class Webdrive < Formula
  desc "Browse and manage files over HTTP from a single binary"
  homepage "https://github.com/cross-entropy-ai/webdrive"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.2.0/webdrive_darwin_arm64.tar.gz"
      sha256 "f3e6f118058154a9cc99d867de045439300878c91bd8be04fade174bca9bec4f"
    else
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.2.0/webdrive_darwin_amd64.tar.gz"
      sha256 "239cd49be89b4b86ca1ff4a940988378aaf384131673fcf72222f7dfffe7e2e4"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.2.0/webdrive_linux_arm64.tar.gz"
      sha256 "08599546044928b797804f2922942ba4dcb3ef50c2954f90b628acefc665cdfd"
    else
      url "https://github.com/cross-entropy-ai/webdrive/releases/download/v0.2.0/webdrive_linux_amd64.tar.gz"
      sha256 "daa5630585886a85c47f34c9a36cc67922bbb9dff3ece5f7ac6a8b61c07f6951"
    end
  end

  def install
    bin.install "webdrive"
  end

  test do
    assert_match "webdrive serves", shell_output("#{bin}/webdrive --help")
  end
end
